<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zianya Nenetzi Trujillo Beltran">
<meta name="author" content="José Eduardo Cruz Campos">
<meta name="author" content="Paola Mildred Martínez Hidalgo">

<title>Almacenes y Minería de Datos: Tarea 02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-04217135fd46c88b22d4bd32c3ae5eaf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Buscar"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul class="collapse">
  <li><a href="#empresa-y-metodología-de-minería-de-datos" id="toc-empresa-y-metodología-de-minería-de-datos" class="nav-link active" data-scroll-target="#empresa-y-metodología-de-minería-de-datos">Empresa y metodología de Minería de Datos</a>
  <ul class="collapse">
  <li><a href="#descripción-general-del-dataset" id="toc-descripción-general-del-dataset" class="nav-link" data-scroll-target="#descripción-general-del-dataset">Descripción general del dataset</a></li>
  </ul></li>
  <li><a href="#medidas-descriptivas-y-análisis-exploratorio-de-datos-eda" id="toc-medidas-descriptivas-y-análisis-exploratorio-de-datos-eda" class="nav-link" data-scroll-target="#medidas-descriptivas-y-análisis-exploratorio-de-datos-eda">Medidas descriptivas y análisis exploratorio de datos (EDA)</a>
  <ul class="collapse">
  <li><a href="#diccionario-de-datos" id="toc-diccionario-de-datos" class="nav-link" data-scroll-target="#diccionario-de-datos">Diccionario de datos</a></li>
  <li><a href="#aplicación-de-crisp-dm-al-dataset-asignado" id="toc-aplicación-de-crisp-dm-al-dataset-asignado" class="nav-link" data-scroll-target="#aplicación-de-crisp-dm-al-dataset-asignado">Aplicación de CRISP-DM al dataset asignado</a></li>
  </ul></li>
  <li><a href="#cálculo-de-medidas-con-visualizaciones-e-interpretación" id="toc-cálculo-de-medidas-con-visualizaciones-e-interpretación" class="nav-link" data-scroll-target="#cálculo-de-medidas-con-visualizaciones-e-interpretación">Cálculo de medidas con visualizaciones e interpretación</a>
  <ul class="collapse">
  <li><a href="#medidas-de-localización" id="toc-medidas-de-localización" class="nav-link" data-scroll-target="#medidas-de-localización">Medidas de localización</a></li>
  <li><a href="#medidas-de-variabilidad" id="toc-medidas-de-variabilidad" class="nav-link" data-scroll-target="#medidas-de-variabilidad">Medidas de variabilidad</a></li>
  <li><a href="#medidas-de-heterogeneidad" id="toc-medidas-de-heterogeneidad" class="nav-link" data-scroll-target="#medidas-de-heterogeneidad">Medidas de heterogeneidad</a></li>
  <li><a href="#medidas-de-concentración" id="toc-medidas-de-concentración" class="nav-link" data-scroll-target="#medidas-de-concentración">Medidas de concentración</a></li>
  </ul></li>
  <li><a href="#correlación" id="toc-correlación" class="nav-link" data-scroll-target="#correlación">Correlación</a></li>
  <li><a href="#hallazgos-importantes-y-limitaciones-del-análisis" id="toc-hallazgos-importantes-y-limitaciones-del-análisis" class="nav-link" data-scroll-target="#hallazgos-importantes-y-limitaciones-del-análisis">Hallazgos importantes y limitaciones del análisis</a></li>
  <li><a href="#reporte-final-hallazgos-y-limitaciones" id="toc-reporte-final-hallazgos-y-limitaciones" class="nav-link" data-scroll-target="#reporte-final-hallazgos-y-limitaciones">Reporte final: hallazgos y limitaciones</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Almacenes y Minería de Datos: Tarea 02</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Zianya Nenetzi Trujillo Beltran </p>
             <p>José Eduardo Cruz Campos </p>
             <p>Paola Mildred Martínez Hidalgo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 de marzo de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="empresa-y-metodología-de-minería-de-datos" class="level1">
<h1>Empresa y metodología de Minería de Datos</h1>
<p>Cada integrante del equipo deberá elegir una empresa distinta en la que le gustaría trabajar e investigar qué metodología utiliza para desarrollar proyectos de Minería de Datos.</p>
<ul>
<li><strong>Zianya:</strong> BBVA aplica CRISP-DM siguiendo 6 pasos:
<ol type="1">
<li>Comprensión del negocio y definición del objetivo</li>
<li>Comprensión de los datos</li>
<li>Análisis y preparación de los datos</li>
<li>Modelado</li>
<li>Obtención de resultados</li>
<li>Despliegue<br>
Fuente: <a href="https://www.bbva.com/es/empresas/como-puede-ayudar-el-data-mining-a-las-empresas/">BBVA</a></li>
</ol></li>
<li><strong>José Eduardo:</strong> Amazon utiliza KDD (Knowledge Discovery in Databases) que consta de 5 etapas:
<ol type="1">
<li>Selección de datos relevantes</li>
<li>Preprocesamiento de datos</li>
<li>Transformación de datos</li>
<li>Minería de datos</li>
<li>Interpretación y evaluación<br>
Fuente: <a href="https://aws.amazon.com/es/what-is/data-mining/">Amazon</a></li>
</ol></li>
<li><strong>Mildred:</strong> Microsoft utiliza principalmente TDSP (Team Data Science Process) que consta de 5 etapas:
<ol type="1">
<li>Entendimiento del negocio</li>
<li>Adquisición y comprensión de datos</li>
<li>Modelado</li>
<li>Implementación</li>
<li>Aceptación<br>
Fuente: <a href="https://learn.microsoft.com/en-us/analysis-services/data-mining/data-mining-ssas?view=asallproducts-allversions">Microsoft</a></li>
</ol></li>
<li><strong>Eric:</strong> Capital One, un banco estadounidense, diseña la metodología en función de que esté fuertemente cargada en automatización tanto en procesos de minería de datos como en procesos de machine learning, así como en la gestión de datos, en función de tener modelos que analizan tendencias de mercado y detección de fraudes o riesgos. Cada equipo es propietario de los recursos que utiliza, por lo que se encarga de su gestión y mantenimiento. Los datos siguen el siguiente ciclo de vida:
<ol type="1">
<li>Registro de Datos en un repositorio centralizado</li>
<li>Clasificación de datos</li>
<li>Ingesta</li>
<li>Modelado</li>
<li>Seguridad y Tokenización</li>
<li>Personalización conforme a cliente</li>
<li>Despliegue Fuente: <a href="https://www.capitalone.com/tech/cloud/data-management-at-scale/">Capital One</a></li>
</ol></li>
</ul>
<section id="descripción-general-del-dataset" class="level2">
<h2 class="anchored" data-anchor-id="descripción-general-del-dataset">Descripción general del dataset</h2>
<p>El dataset RNPDNO-22-08-2023 contiene información oficial sobre personas desaparecidas y no localizadas en México, publicada como dato abierto. Cada fila representa el reporte de una persona desaparecida.</p>
<ul>
<li><strong>Número de filas:</strong> 116945</li>
</ul>
<div id="ad4953e3" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(dataset)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>num_files <span class="op">=</span> df.shape[<span class="dv">0</span>] <span class="co">#obtenemos el numero de filas del csv </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Numero de filas: </span><span class="sc">{</span>num_files<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Numero de filas: 116945</code></pre>
</div>
</div>
<ul>
<li><strong>Número de columnas:</strong> 11</li>
</ul>
<div id="828e97cf" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(dataset)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>num_columns <span class="op">=</span> df.shape[<span class="dv">1</span>] <span class="co">#obtenemos el numero de columnas del csv</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Numero de columnas: </span><span class="sc">{</span>num_columns<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Numero de columnas: 11</code></pre>
</div>
</div>
<ul>
<li><strong>Periodo de fechas cubierto:</strong> Se cubrió desde el periodo del 01-05-1968 al 20-08-2023</li>
</ul>
<div id="285c6d0e" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(dataset)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># eliminamos espacios en blanco de los nombres de las columnas</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>df.columns <span class="op">=</span> df.columns.<span class="bu">str</span>.strip() </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#metemos a una lista las fechas de desaparicion para despues obtener la fecha minima y maxima.</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Fecha de desaparición"</span>] <span class="op">=</span> pd.to_datetime( df[<span class="st">"Fecha de desaparición"</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"</span><span class="sc">%d</span><span class="st">/%m/%Y"</span>, errors<span class="op">=</span><span class="st">"coerce"</span> )</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>fecha_min <span class="op">=</span> df[<span class="st">"Fecha de desaparición"</span>].<span class="bu">min</span>() </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>fecha_max <span class="op">=</span> df[<span class="st">"Fecha de desaparición"</span>].<span class="bu">max</span>()</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Periodo:"</span>, fecha_min, <span class="st">"a"</span>, fecha_max)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Periodo: 1968-05-01 00:00:00 a 2023-08-20 00:00:00</code></pre>
</div>
</div>
<ul>
<li><strong>Unidad de análisis:</strong> En nuestro dataset, cada fila representa el reporte de una persona desaparecida, obteniendo datos como el ID del reporte (Consecutivo Reportes por Persona), Consecutivo registro (num de veces que se reportó), Nombre de la persona, Apellidos, Edad, Sexo, Nacionalidad, Fecha de desaparición, Entidad de desaparición, Autoridad que reportó.</li>
</ul>
<hr>
</section>
</section>
<section id="medidas-descriptivas-y-análisis-exploratorio-de-datos-eda" class="level1">
<h1>Medidas descriptivas y análisis exploratorio de datos (EDA)</h1>
<section id="diccionario-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="diccionario-de-datos">Diccionario de datos</h2>
<p>Crear una tabla que incluya, para cada columna: - Nombre de la columna - Descripción - Tipo de dato (string, entero, float, fecha/hora, booleano) - Tipo estadístico: - Categórica nominal u ordinal - Numérica discreta o continua</p>
<div id="fig-tabla-columnas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tabla-columnas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/tabla_de_columnas.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tabla-columnas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Tabla de columnas
</figcaption>
</figure>
</div>
</section>
<section id="aplicación-de-crisp-dm-al-dataset-asignado" class="level2">
<h2 class="anchored" data-anchor-id="aplicación-de-crisp-dm-al-dataset-asignado">Aplicación de CRISP-DM al dataset asignado</h2>
<section id="business-understanding" class="level3">
<h3 class="anchored" data-anchor-id="business-understanding">Business Understanding</h3>
<section id="contexto-escenario" class="level4">
<h4 class="anchored" data-anchor-id="contexto-escenario">Contexto / Escenario</h4>
<p>México atraviesa una grave crisis de inseguridad con más de 110,965 casos registrados de personas desaparecidas y no localizadas, principalmente vinculadas a problemáticas estructurales como la violencia, el crimen organizado y la impunidad. Este fenómeno presenta características sistemáticas y afecta de manera diferenciada a diversos grupos de la población. El presente análisis se sitúa en un contexto social y analítico, utilizando datos abiertos sobre personas desaparecidas en México. El dataset proporciona información relevante sobre características demográficas (edad, sexo, nacionalidad), así como variables temporales y geográficas (fecha y entidad de desaparición) y las autoridades responsables del reporte. El objetivo de este análisis es identificar estadísticas, tendencias y grupos vulnerables a lo largo del tiempo.</p>
</section>
<section id="situación-problemática" class="level4">
<h4 class="anchored" data-anchor-id="situación-problemática">Situación problemática</h4>
<p>Las desapariciones ocurren frecuentemente con la intervención directa e indirecta de agentes gubernamentales. Estos actores estatales podrían corresponder a una parte de una red de macro-criminalidad en donde se promueven los fines del crimen organizado. El contexto de impunidad en México ha contribuido a la crisis de desapariciones. La falta de información sobre desapariciones es usada para justificar la falta de rendición de cuentas y justicia. Al mirar estos casos más de cerca, se demuestra que oficiales gubernamentales no investigan las desapariciones de una manera oportuna y efectiva como la ley lo requiere. Esto se puede deber a la dificultad de tal investigación o al miedo a llevarla a cabo en un contexto de crímenes violentos. De forma alternativa, la falta de búsqueda o investigación ha sido usada para encubrir el involucramiento de los mismos agentes estatales. La falta de investigación efectiva y la ausencia de justicia perpetúan el ciclo de violencia y desapariciones, dejando a las víctimas y sus familias sin respuestas ni reparación.</p>
<p>Fuente: <a href="https://cla.umn.edu/human-rights/desapariciones-en-mexico">Desapariciones en México - University of Minnesota</a></p>
</section>
<section id="objetivo-de-análisis" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-de-análisis">Objetivo de análisis</h4>
<p>El objetivo de este análisis es entender cómo se comporta el fenómeno de desapariciones en México.</p>
</section>
<section id="necesidades-de-información" class="level4">
<h4 class="anchored" data-anchor-id="necesidades-de-información">Necesidades de información</h4>
<p>En consecuencia, el problema inicial se puede formular así:</p>
<ul>
<li>¿En qué entidades del país ocurren más desapariciones?</li>
<li>¿Existen patrones regionales o zonas de mayor riesgo?</li>
<li>¿Qué grupos de edad son más vulnerables?</li>
<li>¿Hay diferencias por sexo o nacionalidad?</li>
<li>¿Qué autoridades reportan más casos?</li>
<li>¿Cómo han evolucionado las desapariciones a lo largo del tiempo?</li>
</ul>
</section>
</section>
<section id="data-understanding" class="level3">
<h3 class="anchored" data-anchor-id="data-understanding">Data Understanding</h3>
<p>A partir del escenario anterior, como equipo analítico se realiza una exploración inicial del dataset, evaluando la calidad de los datos, valores faltantes e inconsistencias, formulando preguntas como las siguientes:</p>
<section id="sobre-estructura-general-del-dataset" class="level4">
<h4 class="anchored" data-anchor-id="sobre-estructura-general-del-dataset">Sobre estructura general del dataset</h4>
<ul>
<li><p>¿Cuántas filas y columnas tiene el dataset?<br>
(anteriormente vimos que tiene 116945 filas y 11 columnas)</p></li>
<li><p>¿Cuantas variables numéricas y categóricas hay?<br>
(notamos 3 variables numéricas: edad, consecutivo reportes por persona, consecutivo registro; y 8 variables categóricas: nombre, apellido paterno, apellido materno, sexo, nacionalidad, fecha de desaparición, entidad de desaparición, autoridad que reporta)</p></li>
<li><p>¿Existen registros duplicados, datos eliminados o filas incompletas?</p></li>
<li><p>¿Hay inconsistencias en los nombres de entidades o instituciones?</p></li>
</ul>
</section>
<section id="sobre-variables-de-entidades-de-desaparición" class="level4">
<h4 class="anchored" data-anchor-id="sobre-variables-de-entidades-de-desaparición">Sobre variables de entidades de desaparición</h4>
<ul>
<li>¿Cuáles son las entidades con más desapariciones?</li>
<li>¿Cómo se distribuyen las desapariciones a lo largo del tiempo?</li>
</ul>
</section>
<section id="sobre-variables-de-las-instituciones-que-reportan-desapariciones" class="level4">
<h4 class="anchored" data-anchor-id="sobre-variables-de-las-instituciones-que-reportan-desapariciones">Sobre variables de las instituciones que reportan desapariciones</h4>
<ul>
<li>¿Qué autoridades reportan la mayor cantidad de desapariciones?</li>
<li>¿Existen instituciones con mayor registros inconsistentes o muy pocos reportes?</li>
</ul>
</section>
<section id="sobre-variables-características-de-las-personas-desaparecidas" class="level4">
<h4 class="anchored" data-anchor-id="sobre-variables-características-de-las-personas-desaparecidas">Sobre variables características de las personas desaparecidas</h4>
<ul>
<li>¿Qué grupos de edad son más vulnerables a las desapariciones?</li>
<li>¿Qué grupos de sexo y nacionalidad presentan más casos de desaparición?</li>
</ul>
</section>
<section id="sobre-la-calidad-de-los-datos" class="level4">
<h4 class="anchored" data-anchor-id="sobre-la-calidad-de-los-datos">Sobre la calidad de los datos</h4>
<ul>
<li>¿Qué porcentaje de datos faltantes hay en cada columna?</li>
</ul>
</section>
</section>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<!-- Se llevan a cabo procesos de limpieza, transformación de datos, tratamiento de valores nulos y generación de variables derivadas.
 -->
<p>Antes de emplear cualquier técnica de limpieza, necesitamos analizar los datos eliminados, duplicados y vacíos, para contestar las siguientes preguntas:</p>
<ul>
<li><strong>¿Cuál es el porcentaje de faltantes de cada columna?</strong></li>
</ul>
<div id="c44195a3" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(dataset)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#limpiamos el dataset, convirtiendo a NaN en un csv copia</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>faltantes <span class="op">=</span> [ <span class="st">""</span>, <span class="st">" "</span>, <span class="st">"NA"</span>, <span class="st">"N/A"</span>, <span class="st">"SE DESCONOCE"</span>, <span class="st">"ELIMINADO 1"</span>, <span class="st">"ELIMINADO 2"</span>, <span class="st">"ELIMINADO 3"</span>, <span class="st">"ELIMINADO 4"</span>, <span class="st">"ELIMINADO 5"</span>, <span class="st">"ELIMINADO 6"</span>, <span class="st">"ELIMINADO 7"</span>, <span class="st">"ELIMINADO 8"</span>, <span class="st">"ELIMINADO 9"</span>, <span class="st">"ELIMINADO 10"</span> , <span class="st">"ELIMINADO 11"</span>]</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>df_limpio <span class="op">=</span> df.replace(faltantes, np.nan)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>df_limpio <span class="op">=</span> df_limpio.replace(<span class="vs">r"ELIMINADO</span><span class="dv">.</span><span class="op">*</span><span class="vs">"</span>, np.nan, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>df_limpio.to_csv(<span class="st">"dataset_limpio.csv"</span>, index<span class="op">=</span><span class="va">False</span>) </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenemos el porcentaje de valores faltantes por columna</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>faltantes_abs <span class="op">=</span> df_limpio.isna().<span class="bu">sum</span>() <span class="co">#convertimos valores a T/F, y sumamos por columna para obtener el numero de faltantes</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>porcentaje_col <span class="op">=</span> (df_limpio.isna().<span class="bu">sum</span>() <span class="op">/</span> <span class="bu">len</span>(df_limpio)) <span class="op">*</span> <span class="dv">100</span> <span class="co">#porcentaje de faltantes por columna</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>num_faltantes_col <span class="op">=</span> df_limpio.isna().<span class="bu">sum</span>() <span class="co">#numero de faltantes por columna</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>resumen <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Número de faltantes"</span>: num_faltantes_col,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Porcentaje "</span>: porcentaje_col.<span class="bu">round</span>(<span class="dv">0</span>).astype(<span class="bu">int</span>).astype(<span class="bu">str</span>) <span class="op">+</span> <span class="st">" %"</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(resumen.to_string())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                  Número de faltantes Porcentaje 
Consecutivo Reportes por Persona                 5980         5 %
Consecutivo Registro                                0         0 %
Nombre                                          37465        32 %
Primer Apellido                                 37487        32 %
Segundo Apellido                                38908        33 %
Edad                                            42022        36 %
Sexo                                            37460        32 %
Nacionalidad                                    45981        39 %
Fecha de desaparición                           93542        80 %
Entidad de desaparición                         38261        33 %
Autoridad que reportó                           38024        33 %</code></pre>
</div>
</div>
<ul>
<li><strong>¿Cuál es el porcentaje de valores faltantes en general?</strong></li>
</ul>
<div id="75ac656e" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(dataset)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#limpiamos el dataset, convirtiendo a NaN en un csv copia</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>faltantes <span class="op">=</span> [ <span class="st">""</span>, <span class="st">" "</span>, <span class="st">"NA"</span>, <span class="st">"N/A"</span>, <span class="st">"SE DESCONOCE"</span>, <span class="st">"ELIMINADO 1"</span>, <span class="st">"ELIMINADO 2"</span>, <span class="st">"ELIMINADO 3"</span>, <span class="st">"ELIMINADO 4"</span>, <span class="st">"ELIMINADO 5"</span>, <span class="st">"ELIMINADO 6"</span>, <span class="st">"ELIMINADO 7"</span>, <span class="st">"ELIMINADO 8"</span>, <span class="st">"ELIMINADO 9"</span>, <span class="st">"ELIMINADO 10"</span> , <span class="st">"ELIMINADO 11"</span>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>df_limpio <span class="op">=</span> df.replace(faltantes, np.nan)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>df_limpio <span class="op">=</span> df_limpio.replace(<span class="vs">r"ELIMINADO</span><span class="dv">.</span><span class="op">*</span><span class="vs">"</span>, np.nan, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>df_limpio.to_csv(<span class="st">"dataset_limpio.csv"</span>, index<span class="op">=</span><span class="va">False</span>) </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenemos el porcentaje total de valores faltantes en el dataset</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>total_celdas <span class="op">=</span> df_limpio.shape[<span class="dv">0</span>] <span class="op">*</span> df_limpio.shape[<span class="dv">1</span>]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>total_faltantes <span class="op">=</span> df_limpio.isna().<span class="bu">sum</span>().<span class="bu">sum</span>() <span class="co">#sumamos el total de datos faltantes en todo el dataset</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>porcentaje_total <span class="op">=</span> (total_faltantes <span class="op">/</span> total_celdas) <span class="op">*</span> <span class="dv">100</span> <span class="co"># sacamos el porcentaje</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">""</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Número total de datos faltantes: </span><span class="sc">{</span>total_faltantes<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Porcentaje total de datos faltantes: </span><span class="sc">{</span><span class="bu">round</span>(porcentaje_total)<span class="sc">}</span><span class="ss"> %"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Número total de datos faltantes: 415130
Porcentaje total de datos faltantes: 32 %</code></pre>
</div>
</div>
<ul>
<li><strong>¿Cuál es el patrón de ausencia?</strong></li>
</ul>
<p>Se identifican distintos patrones de ausencia en el dataset. La variable fecha de desaparición tiene el mayor porcentaje de valores faltantes (80%), lo que sugiere un patrón no aleatorio asociado a fallas en el registro. También existen casos con múltiples datos faltantes simultáneamente, especialmente en registros con varias columnas con el valor “ELIMINADO”, indicando ausencia agrupada por fila. Por otra parte variables como edad, sexo y nacionalidad muestran un porcentaje faltante entre 30% y 40% de forma más dispersa, lo que puede apuntar a problemas de captura o diferencias entre fuentes. En conjunto, los datos faltantes responden a factores estructurales y no son completamente aleatorios.</p>
<ul>
<li><strong>¿Cuál sería el mecanismo de ausencia más probable?</strong></li>
</ul>
<p>En el caso de la variable Fecha de desaparición su porcentaje de valores faltantes (80%) indica un mecanismo de tipo MAR (Missing At Random), ya que su ausencia probablemente depende de factores como la institución que reporta, la entidad o el periodo de registro.</p>
<p>Por otro lado, los registros que contienen valores como “ELIMINADO” evidencian un mecanismo de tipo MNAR (Missing Not At Random), dado que la ausencia de información puede deberse a procesos intencionales de anonimización o censura.</p>
<p>Finalmente, variables como edad, sexo y nacionalidad presentan un comportamiento consistente con un mecanismo predominantemente MAR, posiblemente asociado a inconsistencias en la captura de datos o diferencias en la calidad de las fuentes.</p>
<div class="nota">
<p><strong>Nota:</strong> La identificación del mecanismo de ausencia es crucial para determinar las estrategias de limpieza y análisis, ya que cada tipo de mecanismo requiere enfoques diferentes para manejar los datos faltantes sin introducir sesgos significativos.</p>
<ul>
<li>MCAR: faltan datos al azar</li>
<li>MAR: faltan datos dependiendo de otra variable</li>
<li>MNAR: faltan datos porque justo ese dato es problemático</li>
</ul>
</div>
<ul>
<li><strong>¿Qué decisión se puede tomar respecto a los valores faltantes y por qué?</strong></li>
</ul>
<p>No podemos eliminar observaciones incompletas puesto que la mayoría el 80 % de la columna de Fecha de desaparición está incompleta, por lo que perderíamos el 80% de la información total. La imputación simple mediante media, mediana o moda no resulta adecuada para la variable Fecha de desaparición puesto que generaría falsas concentraciones de datos en determinados periodos de tiempo, distorsionando las tendencias reales y comprometiendo la validez del análisis. Por lo que se opta por mantener los valores faltantes remplazándolos como NaN para mantener la integridad de los datos disponibles y evitar sesgos a través de imputaciones incorrectas. Y eliminamos las filas que tienen valores como “ELIMINADO” en todas sus columnas, ya que estas filas no aportan información útil para el análisis y su presencia podría generar ruido o confusión en los resultados. Finalmente, el poco porcentaje de registros con fecha disponible se pueden utilizar para el análisis temporal, permitiendo estudiar tendencias y evolución en el tiempo además de el análisis demográfico, geográfico e institucional que se puede realizar con la mayoría del dataset, maximizando el aprovechamiento de la información disponible.</p>
<ul>
<li><strong>¿Cómo podemos encontrar registros duplicados?</strong></li>
</ul>
<p>Para encontrar registros duplicados primero necesitamos limpiar el dataset quitando filas que contengan todos sus datos como ELIMINADO y reemplazando los vacíos por NaN, para luego buscar filas que coincidan en las siguientes columnas: nombre, apellido paterno, apellido materno, fecha de desaparición, entidad de desaparición y autoridad que reportó. Estas columnas se consideran relevantes para identificar registros duplicados, ya que una persona puede tener múltiples reportes en diferentes instituciones o momentos, pero si coinciden en estas características clave es probable que se trate del mismo caso registrado varias veces.</p>
<div id="daf3c262" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Cargamos dataset </span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">"RNPDNO-22-08-2023.csv"</span>, encoding<span class="op">=</span><span class="st">"latin-1"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total de registros iniciales:"</span>, <span class="bu">len</span>(dataset))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Reemplazamos vacíos por NaN</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> dataset.replace(<span class="vs">r'</span><span class="dv">^\s</span><span class="op">*</span><span class="dv">$</span><span class="vs">'</span>, np.nan, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Reemplazamos "ELIMINADO" por NaN</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> dataset.replace(to_replace<span class="op">=</span><span class="st">"ELIMINADO.*"</span>, value<span class="op">=</span>np.nan, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Eliminamos filas donde todas las columnas relevantes son NaN (registros ELIMINADO)</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>columnas_relevantes <span class="op">=</span> [</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Nombre"</span>, <span class="st">"Primer Apellido"</span>, <span class="st">"Segundo Apellido"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Fecha de desaparición"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Autoridad que reportó"</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> dataset.dropna(subset<span class="op">=</span>columnas_relevantes, how<span class="op">=</span><span class="st">"all"</span>)</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalizamos texto</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>cols_texto <span class="op">=</span> [<span class="st">"Sexo"</span>, <span class="st">"Nacionalidad"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Autoridad que reportó"</span>]</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cols_texto:</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    dataset[col] <span class="op">=</span> dataset[col].<span class="bu">str</span>.upper().<span class="bu">str</span>.strip()</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. cambiamos INDETERMINADO como NaN</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>dataset[<span class="st">"Sexo"</span>] <span class="op">=</span> dataset[<span class="st">"Sexo"</span>].replace(<span class="st">"INDETERMINADO"</span>, np.nan)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Convertimos la columna de consecutivo a entero nullable</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>dataset[<span class="st">"Consecutivo Reportes por Persona"</span>] <span class="op">=</span> dataset[<span class="st">"Consecutivo Reportes por Persona"</span>].astype(<span class="st">"Int64"</span>)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. Buscamos si hay duplicados </span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>duplicados <span class="op">=</span> dataset[dataset.duplicated(</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>    subset<span class="op">=</span>[</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Nombre"</span>, <span class="st">"Primer Apellido"</span>, <span class="st">"Segundo Apellido"</span>,</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Fecha de desaparición"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Autoridad que reportó"</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>    keep<span class="op">=</span><span class="va">False</span></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Ejemplo de registros duplicados:")</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="co"># print(duplicados.head(20))</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Duplicados encontrados:"</span>, <span class="bu">len</span>(duplicados))</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. Eliminamos duplicados</span></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> dataset.drop_duplicates(</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>    subset<span class="op">=</span>[</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Nombre"</span>, <span class="st">"Primer Apellido"</span>, <span class="st">"Segundo Apellido"</span>,</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Fecha de desaparición"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Autoridad que reportó"</span></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>    keep<span class="op">=</span><span class="st">"first"</span> </span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. Confirmamos que ya no hay duplicados</span></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>duplicados <span class="op">=</span> dataset[dataset.duplicated(</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>    subset<span class="op">=</span>[</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Nombre"</span>, <span class="st">"Primer Apellido"</span>, <span class="st">"Segundo Apellido"</span>,</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Fecha de desaparición"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Autoridad que reportó"</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>    keep<span class="op">=</span><span class="va">False</span></span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Nuevos duplicados encontrados:"</span>, <span class="bu">len</span>(duplicados))</span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a><span class="co"># 9. Guardar dataset limpio</span></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>dataset.to_csv(<span class="st">"dataset_limpio.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dataset guardado como dataset_limpio.csv"</span>)</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total de registros finales:"</span>, <span class="bu">len</span>(dataset))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Total de registros iniciales: 116945
Duplicados encontrados: 385
Nuevos duplicados encontrados: 0
Dataset guardado como dataset_limpio.csv
Total de registros finales: 79285</code></pre>
</div>
</div>
<ul>
<li><strong>¿Qué acciones se tomaron respecto a los registros duplicados y por qué?</strong></li>
</ul>
<p>Eliminamos únicamente los registros que coincidieran en nombre, apellido paterno, materno, fecha de desaparición, Entidad de desaparición y Autoridad que reportó puesto que el nombre y apellido no son suficiente para eliminar registros duplicados pues esa persona puede tener reportes en diferentes instituciones.</p>
</section>
<section id="modelling" class="level3">
<h3 class="anchored" data-anchor-id="modelling">Modelling</h3>
<p>Se proponen técnicas como clustering y análisis de series de tiempo para el análisis del fenómeno. A continuación, se muestra una implementación inicial de ambos modelos para identificar patrones en la edad y volumen de desapariciones.</p>
<section id="análisis-de-series-de-tiempo" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-series-de-tiempo">1. Análisis de Series de Tiempo</h4>
<p>Este modelo busca identificar la tendencia temporal del volumen de personas desaparecidas a lo largo de los meses.</p>
<div id="d88aecb3" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Asumiendo que df_limpio es nuestro dataframe después del Data Preparation</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupamos por año y mes usando la fecha de desaparición</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">"Fecha de desaparición"</span> <span class="kw">in</span> df_limpio.columns:</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    df_limpio[<span class="st">"Fecha de desaparición"</span>] <span class="op">=</span> pd.to_datetime(df_limpio[<span class="st">"Fecha de desaparición"</span>], errors<span class="op">=</span><span class="st">"coerce"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    df_ts <span class="op">=</span> df_limpio.dropna(subset<span class="op">=</span>[<span class="st">"Fecha de desaparición"</span>]).copy()</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    serie_tiempo <span class="op">=</span> df_ts.groupby(df_ts[<span class="st">"Fecha de desaparición"</span>].dt.to_period(<span class="st">"M"</span>)).size().reset_index(name<span class="op">=</span><span class="st">"Total"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    serie_tiempo[<span class="st">"Fecha de desaparición"</span>] <span class="op">=</span> serie_tiempo[<span class="st">"Fecha de desaparición"</span>].dt.to_timestamp()</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    plt.plot(serie_tiempo[<span class="st">"Fecha de desaparición"</span>], serie_tiempo[<span class="st">"Total"</span>], marker<span class="op">=</span><span class="st">''</span>, linestyle<span class="op">=</span><span class="st">'-'</span>, color<span class="op">=</span><span class="st">'b'</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"Tendencia Histórica de Desapariciones (Agrupado por Mes)"</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Año y Mes"</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Cantidad de Desapariciones"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"La columna 'Fecha de desaparición' no está disponible para analizar."</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>    sexo_counts.plot(kind<span class="op">=</span><span class="st">'pie'</span>, autopct<span class="op">=</span><span class="st">'</span><span class="sc">%1.1f%%</span><span class="st">'</span>, colors<span class="op">=</span>[<span class="st">'#3266ad'</span>, <span class="st">'#e05c5c'</span>])</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">'Proporción por sexo'</span>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">''</span>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    plt.show()     </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="965" height="524" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>De esta grafica podemos encontrar que el porcentaje de hombres desaparecidos es mayor al de mujeres, sin embargo, el porcentaje de datos faltantes en la columna de sexo es del 30%, por lo que esta información no se puede considerar completamente confiable.</p>
</section>
<section id="clustering-k-means" class="level4">
<h4 class="anchored" data-anchor-id="clustering-k-means">2. Clustering (K-Means)</h4>
<p>Agruparemos las entidades federativas (estados) con base en dos características numéricas: la <strong>cantidad total de desapariciones</strong> y la <strong>edad promedio</strong> de los desaparecidos.</p>
<div id="dcb6ed95" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> KMeans</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">"Entidad de desaparición"</span> <span class="kw">in</span> df_limpio.columns <span class="kw">and</span> <span class="st">"Edad"</span> <span class="kw">in</span> df_limpio.columns:</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    df_limpio[<span class="st">"Edad"</span>] <span class="op">=</span> pd.to_numeric(df_limpio[<span class="st">"Edad"</span>], errors<span class="op">=</span><span class="st">"coerce"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    df_cluster <span class="op">=</span> df_limpio.groupby(<span class="st">"Entidad de desaparición"</span>).agg({</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Edad"</span>: <span class="st">"mean"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Consecutivo Registro"</span>: <span class="st">"count"</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    }).reset_index()</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    df_cluster.rename(columns<span class="op">=</span>{<span class="st">"Consecutivo Registro"</span>: <span class="st">"Total_Desapariciones"</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    df_cluster.dropna(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    X_scaled <span class="op">=</span> scaler.fit_transform(df_cluster[[<span class="st">"Edad"</span>, <span class="st">"Total_Desapariciones"</span>]])</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    kmeans <span class="op">=</span> KMeans(n_clusters<span class="op">=</span><span class="dv">4</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    df_cluster[<span class="st">"Cluster"</span>] <span class="op">=</span> kmeans.fit_predict(X_scaled)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Visualizar los clusters</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    sns.scatterplot(data<span class="op">=</span>df_cluster, x<span class="op">=</span><span class="st">"Edad"</span>, y<span class="op">=</span><span class="st">"Total_Desapariciones"</span>, hue<span class="op">=</span><span class="st">"Cluster"</span>, palette<span class="op">=</span><span class="st">"viridis"</span>, s<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"Clustering de Entidades: Volumen de Desapariciones vs Edad Promedio"</span>)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Edad Promedio"</span>)</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Total de Desapariciones"</span>)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, txt <span class="kw">in</span> <span class="bu">enumerate</span>(df_cluster[<span class="st">"Entidad de desaparición"</span>]):</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> df_cluster[<span class="st">"Total_Desapariciones"</span>][i] <span class="op">&gt;</span> df_cluster[<span class="st">"Total_Desapariciones"</span>].quantile(<span class="fl">0.85</span>): <span class="co"># Solo estados con alto volumen</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>            plt.annotate(txt, (df_cluster[<span class="st">"Edad"</span>][i], df_cluster[<span class="st">"Total_Desapariciones"</span>][i]), fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Faltan columnas numéricas requeridas para el clustering."</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="833" height="523" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="clasificación-con-árboles-de-decisión" class="level4">
<h4 class="anchored" data-anchor-id="clasificación-con-árboles-de-decisión">3. Clasificación con Árboles de Decisión</h4>
<p>Este modelo ayuda a identificar reglas que separan a las personas desaparecidas según su sexo, utilizando su Edad y el Estado donde desaparecieron.</p>
<div id="16edefc4" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier, plot_tree</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">"Sexo"</span> <span class="kw">in</span> df_limpio.columns <span class="kw">and</span> <span class="st">"Entidad de desaparición"</span> <span class="kw">in</span> df_limpio.columns <span class="kw">and</span> <span class="st">"Edad"</span> <span class="kw">in</span> df_limpio.columns:</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    df_tree <span class="op">=</span> df_limpio.dropna(subset<span class="op">=</span>[<span class="st">"Edad"</span>, <span class="st">"Sexo"</span>, <span class="st">"Entidad de desaparición"</span>]).copy()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    df_tree <span class="op">=</span> df_tree[df_tree[<span class="st">"Sexo"</span>].isin([<span class="st">"HOMBRE"</span>, <span class="st">"MUJER"</span>])]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    le_sexo <span class="op">=</span> LabelEncoder()</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    df_tree[<span class="st">"Sexo_encoded"</span>] <span class="op">=</span> le_sexo.fit_transform(df_tree[<span class="st">"Sexo"</span>])</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    le_entidad <span class="op">=</span> LabelEncoder()</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    df_tree[<span class="st">"Entidad_encoded"</span>] <span class="op">=</span> le_entidad.fit_transform(df_tree[<span class="st">"Entidad de desaparición"</span>])</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> df_tree[[<span class="st">"Edad"</span>, <span class="st">"Entidad_encoded"</span>]]</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> df_tree[<span class="st">"Sexo_encoded"</span>]</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    clf <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">42</span>, class_weight<span class="op">=</span><span class="st">"balanced"</span>)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    clf.fit(X, y)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">8</span>))</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    plot_tree(clf, </span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>              feature_names<span class="op">=</span>[<span class="st">"Edad"</span>, <span class="st">"Entidad (Codificada)"</span>], </span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>              class_names<span class="op">=</span>le_sexo.classes_, </span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>              filled<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>              rounded<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>              fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>              proportion<span class="op">=</span><span class="va">True</span>) <span class="co"># Mostrar en proporciones para mayor legibilidad</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"Árbol de Decisión: Reglas del perfil de Desaparición por Sexo"</span>)</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Faltan columnas necesarias para ejecutar el Árbol de Decisión."</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" width="1212" height="634" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="predicción-de-nacionalidad-random-forest" class="level4">
<h4 class="anchored" data-anchor-id="predicción-de-nacionalidad-random-forest">4. Predicción de Nacionalidad (Random Forest)</h4>
<p>Este modelo evalúa la importancia de variables demográficas y geográficas para predecir si una persona reportada es de origen extranjero o mexicano, ayudando a detectar patrones de migración vulnerada.</p>
<div id="0cf05e5a" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">"Nacionalidad"</span> <span class="kw">in</span> df_limpio.columns <span class="kw">and</span> <span class="st">"Entidad de desaparición"</span> <span class="kw">in</span> df_limpio.columns:</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    df_rf <span class="op">=</span> df_limpio.dropna(subset<span class="op">=</span>[<span class="st">"Edad"</span>, <span class="st">"Sexo"</span>, <span class="st">"Entidad de desaparición"</span>, <span class="st">"Nacionalidad"</span>]).copy()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Binarizamos Nacionalidad: 0 = Mexicana, 1 = Extranjera/Otra</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    es_mexicano <span class="op">=</span> df_rf[<span class="st">"Nacionalidad"</span>].<span class="bu">str</span>.contains(<span class="st">"MEXICAN"</span>, case<span class="op">=</span><span class="va">False</span>, na<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    df_rf[<span class="st">"Es_Extranjero"</span>] <span class="op">=</span> np.where(es_mexicano, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    df_rf <span class="op">=</span> df_rf[df_rf[<span class="st">"Sexo"</span>].isin([<span class="st">"HOMBRE"</span>, <span class="st">"MUJER"</span>])]</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    le_sexo <span class="op">=</span> LabelEncoder()</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    df_rf[<span class="st">"Sexo_encoded"</span>] <span class="op">=</span> le_sexo.fit_transform(df_rf[<span class="st">"Sexo"</span>])</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    le_entidad <span class="op">=</span> LabelEncoder()</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    df_rf[<span class="st">"Entidad_encoded"</span>] <span class="op">=</span> le_entidad.fit_transform(df_rf[<span class="st">"Entidad de desaparición"</span>])</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> df_rf[[<span class="st">"Edad"</span>, <span class="st">"Sexo_encoded"</span>, <span class="st">"Entidad_encoded"</span>]]</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> df_rf[<span class="st">"Es_Extranjero"</span>]</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Entrenamiento de Bosque Aleatorio balanceado para manejar grupos minoritarios (extranjeros)</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    rf <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">50</span>, max_depth<span class="op">=</span><span class="dv">5</span>, class_weight<span class="op">=</span><span class="st">"balanced"</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    rf.fit(X, y)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Obtenemos la importancia de cada variable (cuál predice mejor el origen)</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    importances <span class="op">=</span> rf.feature_importances_</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    features <span class="op">=</span> [<span class="st">"Edad"</span>, <span class="st">"Sexo"</span>, <span class="st">"Entidad"</span>]</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>    plt.barh(features, importances, color<span class="op">=</span><span class="st">'teal'</span>)</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"Importancia de Factores para Predecir Población Extranjera"</span>)</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Nivel de Importancia (Importancia de Gini)"</span>)</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Faltan columnas necesarias para el modelo de Nacionalidad."</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="674" height="450" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="evaluation" class="level3">
<h3 class="anchored" data-anchor-id="evaluation">Evaluation</h3>
<p>Con base en la implementación de los modelos y el EDA previo, se establecen las siguientes conclusiones y observaciones para el cumplimiento de los <strong>Objetivos del Negocio</strong>:</p>
<ol type="1">
<li><strong>Cumplimiento de las Necesidades de Información:</strong>
<ul>
<li>Los diversos modelos (Clustering, Árboles) consiguieron responder activamente “qué entidades corren mayor riesgo” y “cuáles grupos son vulnerables (edad y género)”. Las reglas visuales del árbol de decisión ayudan a los tomadores de decisiones a entender demográficamente los riesgos.</li>
</ul></li>
<li><strong>Limitaciones por la Calidad de los Datos:</strong>
<ul>
<li><strong>Series de Tiempo y Fechas:</strong> El análisis temporal, aunque permite observar picos institucionales de reportes, se encuentra profundamente sesgado. El haber documentado un 80% de datos faltantes bajo un comportamiento <code>MAR</code> u ocultamiento <code>MNAR</code> indica que los valles en la gráfica de tiempo pueden no representar baja criminalidad, sino ineficiencia burocrática temporal o épocas de no-registro de las autoridades.</li>
</ul></li>
<li><strong>Confiabilidad Técnica y Sesgos de Clase:</strong>
<ul>
<li><strong>Random Forest (Nacionalidad):</strong> El intento de predecir población extranjera devela un fuerte desequilibrio estructural (imbalance de clases). La evaluación de un modelo sobre estos datos no se puede confiar únicamente en su “Precisión” (Accuracy), ya que el ~98% de personas siempre serán de origen mexicano en los registros. Sin embargo, permite evaluar mediante Importancia de Variables (Feature Importances) que factores como la geografía son sumamente determinantes para extranjeros vulnerados durante flujos migratorios.</li>
</ul></li>
</ol>
<p>En conjunto, el modelado extrajo valor real de los datos disponibles, no obstante, las fallas institucionales en la captura de registros dictan que estas conclusiones representan únicamente los crímenes efectivamente “reconocidos” y capturados, más no el volumen real no reportado, y se deben presentar bajo este contexto ético.</p>
</section>
<section id="deployment" class="level3">
<h3 class="anchored" data-anchor-id="deployment">Deployment</h3>
<p>El despliegue (<em>Deployment</em>) de este proyecto de Minería de Datos no concluye en la implementación de un software predictivo automatizado tradicional, sino en la <strong>disponibilidad de inteligencia analítica y de datos limpios</strong> para tomadores de decisiones, investigadores y ONGs.</p>
<p>Las acciones de despliegue para este análisis consisten en:</p>
<ol type="1">
<li><strong>Reporte Técnico y Reproducibilidad:</strong> Integración de todo el flujo de trabajo (desde la carga de datos hasta la Evaluación) en este documento dinámico (<code>.qmd</code>). Al compilarse, despliega un reporte HTML o PDF con código reproducible.</li>
<li><strong>Suministro del Pipeline de Datos (Data Asset):</strong> Exportación y publicación del conjunto de datos ya depurado (<code>dataset_limpio.csv</code>), garantizando que equipos externos puedan montar sus propios algoritmos sobre una base con formatos homologados (fechas numéricas, strings estandarizados y nulos declarados bajo la metodología MAR/MNAR).</li>
<li><strong>Despliegue de Reglas de Decisión (Insights):</strong> Las reglas extraídas en la fase de modelaje (el Árbol de Decisión y la segmentación de K-Means) pueden ser desplegadas como <em>alertas paramétricas</em> en sistemas de información del gobierno. Por ejemplo, al recibirse un nuevo reporte en la Fiscalía, el sistema puede alertar automáticamente sobre un riesgo agudo si la persona ingresada cruza los umbrales de alta vulnerabilidad detectados por nuestros modelos demográficos.</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="cálculo-de-medidas-con-visualizaciones-e-interpretación" class="level1">
<h1>Cálculo de medidas con visualizaciones e interpretación</h1>
<!--Calcular las medidas vistas en clase, acompañarlas con su respectiva gráfica e incluir una
interpretación breve, formal y contextualizada en el caso del dataset de personas desaparecidas asignado al equipo.-->
<p>Se clasificaron las variables del dataset en cuantitativas y cualitativas con el fin de determinar las medidas y visualizaciones adecuadas, consultar la <a href="#fig-tabla-columnas" class="quarto-xref">Figura&nbsp;1</a>.</p>
<ul>
<li><strong>Cualitativas</strong>
<ul>
<li><em>Nominales:</em> sexo, nacionalidad, entidad, autoridad que reportó</li>
<li><em>Ordinales:</em> no tenemos.</li>
</ul></li>
<li><strong>Cuantitativas</strong>
<ul>
<li><em>Discretas:</em> consecutivo registro, edad</li>
<li><em>Continuas:</em> no tenemos</li>
</ul></li>
</ul>
<div class="nota">
<p><strong>Nota:</strong> La variable fecha de desaparición se clasifica como una variable temporal, ya que representa un punto específico en el tiempo y no una cantidad medible.</p>
<p>Sin embargo, esta variable puede transformarse en nuevas variables derivadas, como año y mes, las cuales permiten realizar análisis cuantitativos y categóricos. Por ejemplo, el mes puede utilizarse como variable categórica ordinal para identificar patrones estacionales en las desapariciones.</p>
</div>
<div class="nota">
<p><strong>Nota:</strong> Las variables nombre, primer apellido, segundo apellido y consecutivo de reportes por persona (ID) fueron clasificadas como variables identificadoras.</p>
<p>Estas variables no fueron consideradas en el análisis estadístico, ya que su función es únicamente distinguir registros individuales.</p>
<p>Asimismo, no son susceptibles de análisis mediante medidas estadísticas ni aportan valor en la generación de visualizaciones, debido a que no permiten identificar patrones, tendencias o relaciones significativas dentro del dataset.</p>
</div>
<section id="medidas-de-localización" class="level2">
<h2 class="anchored" data-anchor-id="medidas-de-localización">Medidas de localización</h2>
<p>Para el análisis de las medidas de localización se utilizó la variable edad, calculando la media, mediana y moda. A partir del histograma, se observa que la edad con mayor frecuencia de desaparición es de 18 años (moda), lo cual sugiere una concentración preocupante en la población adolescente.</p>
<p>Asimismo, la mediana (29) es menor que la media (31.7), lo que indica que la distribución presenta un sesgo hacia la derecha. Esto implica que existen algunos casos de mayor edad que elevan el promedio.</p>
<p>Por otro lado, los percentiles permiten comprender mejor la distribución de la variable. Por ejemplo, el percentil 90 indica que el 90% de las personas desaparecidas tiene una edad menor o igual a 52 años. Estas medidas son útiles para identificar valores extremos y analizar la dispersión de los datos.</p>
<div id="dd5c0399" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar dataset limpio</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'dataset_limpio.csv'</span>, encoding<span class="op">=</span><span class="st">'latin1'</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Edad'</span>] <span class="op">=</span> pd.to_numeric(df[<span class="st">'Edad'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>edad <span class="op">=</span> df[<span class="st">'Edad'</span>].dropna().values</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de localización </span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>mean   <span class="op">=</span> edad.mean()</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>median <span class="op">=</span> np.median(edad)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Moda aproximada: centro del bin con mayor frecuencia</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>counts, bin_edges <span class="op">=</span> np.histogram(edad, bins<span class="op">=</span>bins)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>max_bin_idx <span class="op">=</span> np.argmax(counts)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>mode_approx <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> (bin_edges[max_bin_idx] <span class="op">+</span> bin_edges[max_bin_idx <span class="op">+</span> <span class="dv">1</span>])</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Media            = </span><span class="sc">{</span>mean<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mediana          = </span><span class="sc">{</span>median<span class="sc">:.0f}</span><span class="ss"> años"</span>)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Moda (aprox)     = </span><span class="sc">{</span>mode_approx<span class="sc">:.0f}</span><span class="ss"> años"</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma con líneas de localización </span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>plt.hist(edad, bins<span class="op">=</span>bins, alpha<span class="op">=</span><span class="fl">0.45</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Personas desaparecidas en México: histograma de edad"</span>)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Edad (años)"</span>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frecuencia"</span>)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>plt.axvline(mean,        color<span class="op">=</span><span class="st">"tab:blue"</span>,   linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"Media = </span><span class="sc">{</span>mean<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>plt.axvline(median,      color<span class="op">=</span><span class="st">"tab:orange"</span>, linestyle<span class="op">=</span><span class="st">"-"</span>,  linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"Mediana = </span><span class="sc">{</span>median<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>plt.axvline(mode_approx, color<span class="op">=</span><span class="st">"tab:red"</span>,  linestyle<span class="op">=</span><span class="st">":"</span>,  linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"Moda (aprox) = </span><span class="sc">{</span>mode_approx<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a><span class="co"># ECDF para percentiles y cola</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>x_sorted <span class="op">=</span> np.sort(edad)</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> np.arange(<span class="dv">1</span>, x_sorted.size <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> x_sorted.size</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>plt.step(x_sorted, y, where<span class="op">=</span><span class="st">"post"</span>)</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Personas desaparecidas en México: ECDF de edad"</span>)</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Edad (años)"</span>)</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Proporción acumulada"</span>)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="fl">1.01</span>)</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Percentiles</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>p25, p50, p75, p90, p95 <span class="op">=</span> np.quantile(edad, [<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>])</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P25=</span><span class="sc">{</span>p25<span class="sc">:.0f}</span><span class="ss"> años,  P50=</span><span class="sc">{</span>p50<span class="sc">:.0f}</span><span class="ss"> años,  P75=</span><span class="sc">{</span>p75<span class="sc">:.0f}</span><span class="ss"> años"</span>)</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P90=</span><span class="sc">{</span>p90<span class="sc">:.0f}</span><span class="ss"> años,  P95=</span><span class="sc">{</span>p95<span class="sc">:.0f}</span><span class="ss"> años"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Media            = 31.71 años
Mediana          = 29 años
Moda (aprox)     = 18 años</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-12-output-2.png" width="662" height="470" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-12-output-3.png" width="663" height="470" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>P25=21 años,  P50=29 años,  P75=40 años
P90=52 años,  P95=60 años</code></pre>
</div>
</div>
<p>Finalmente, en ambas gráficas se observa claramente la presencia de un sesgo. Esto se debe a un valor atípico considerablemente alejado del resto (1832), lo cual puede confirmarse con el siguiente código.</p>
<div id="06d86177" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'Edad'</span>].<span class="bu">max</span>())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>1832.0</code></pre>
</div>
</div>
</section>
<section id="medidas-de-variabilidad" class="level2">
<h2 class="anchored" data-anchor-id="medidas-de-variabilidad">Medidas de variabilidad</h2>
<section id="varianza-y-desviación-estándar" class="level3">
<h3 class="anchored" data-anchor-id="varianza-y-desviación-estándar">Varianza y desviación estándar</h3>
<p>Para interpretar la varianza nos ayudamos de la desviación estandar, en este caso tenemos una desviación estándar de 17 años, esto significa que las edades de las personas registradas como desaparecidas se dispersan, en promedio, aproximadamente 17 años por encima o por debajo de la media. Esto implica que el rango típico de edades oscila entre los 14 años (31 − 17) y los 48 años (31 + 17), abarcando desde adolescentes hasta adultos de mediana edad como el perfil más frecuente.</p>
<p>Esto refleja que la desaparición de personas en México no se limita a un grupo específico, sino que afecta a individuos en distintas edades, sin embargo se puede ver una mayor concentración en edades jóvenes, lo cual vimos también con la moda, esto sugiere que la población adolescente y adulta joven enfrenta un riesgo particularmente elevado.</p>
<div id="374f8adc" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar CSV limpio</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'dataset_limpio.csv'</span>, encoding<span class="op">=</span><span class="st">'latin1'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Edad'</span>] <span class="op">=</span> pd.to_numeric(df[<span class="st">'Edad'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>edad <span class="op">=</span> df[<span class="st">'Edad'</span>].dropna()</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de variabilidad </span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>varianza <span class="op">=</span> edad.var(ddof<span class="op">=</span><span class="dv">1</span>)        </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>desv_std <span class="op">=</span> edad.std(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>media    <span class="op">=</span> edad.mean()</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Varianza:            </span><span class="sc">{</span>varianza<span class="sc">:.4f}</span><span class="ss"> años"</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Desviación estándar: </span><span class="sc">{</span>desv_std<span class="sc">:.4f}</span><span class="ss"> años"</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Media:               </span><span class="sc">{</span>media<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfica </span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>ax.hist(edad, bins<span class="op">=</span><span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">121</span>, <span class="dv">5</span>), color<span class="op">=</span><span class="st">'#3266ad'</span>, alpha<span class="op">=</span><span class="fl">0.75</span>,</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">'white'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Distribución de edades'</span>)</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Línea de la media</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>ax.axvline(media, color<span class="op">=</span><span class="st">'#E24B4A'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, linestyle<span class="op">=</span><span class="st">'--'</span>,</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f'Media: </span><span class="sc">{</span>media<span class="sc">:.1f}</span><span class="ss"> años'</span>)</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Banda de ±1 desviación estándar</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>ax.axvspan(media <span class="op">-</span> desv_std, media <span class="op">+</span> desv_std,</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>           alpha<span class="op">=</span><span class="fl">0.15</span>, color<span class="op">=</span><span class="st">'#EF9F27'</span>,</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f'±1 σ (</span><span class="sc">{</span>media <span class="op">-</span> desv_std<span class="sc">:.1f}</span><span class="ss"> – </span><span class="sc">{</span>media <span class="op">+</span> desv_std<span class="sc">:.1f}</span><span class="ss"> años)'</span>)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Varianza y desviación estándar — edad de personas desaparecidas'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Edad (años)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Número de personas'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> x, _: <span class="ss">f'</span><span class="sc">{</span><span class="bu">int</span>(x)<span class="sc">:,}</span><span class="ss">'</span>))</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'variabilidad_edad.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza:            292.7119 años
Desviación estándar: 17.1088 años
Media:               31.71 años</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-14-output-2.png" width="949" height="469" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="cuartiles-rango-e-iqr" class="level3">
<h3 class="anchored" data-anchor-id="cuartiles-rango-e-iqr">Cuartiles, Rango e IQR</h3>
<ul>
<li><p><strong>Cuartiles</strong> El primer cuartil (Q1) de 21 años indica que el 25% de las personas desaparecidas tenía 21 años o menos al momento de su desaparición, lo que evidencia una concentración significativa de casos en población joven. El tercer cuartil (Q3) de 40 años señala que el 75% de los registros corresponde a personas de 40 años o menos, confirmando que la desaparición de personas en México afecta predominantemente a individuos en etapa productiva y juvenil.</p></li>
<li><p><strong>Rango Intercuartílico (IQR)</strong> El IQR de 19 años representa la amplitud del 50% central de los datos, es decir, la mitad de las personas desaparecidas tenía entre 21 y 40 años,mostrando que la mayor concentración de edades se encuentra dentro de ese intervalo.</p></li>
<li><p><strong>Rango y valores atípicos</strong> Los límites calculados a partir del IQR establecen que valores fuera del rango de −7.50 a 68.50 años se consideran atípicos estadísticamente. Dado que una edad negativa no tiene interpretación posible, el límite inferior efectivo es 0 años. Esto significa que cualquier persona registrada con más de 68 años representa un caso atípico dentro del dataset, esto puede implicar que dichos casos sean errores o que se trate de desapariciones menos frecuentes en grupos de edad avanzada.</p></li>
</ul>
<div id="394c645f" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar CSV limpio</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'dataset_limpio.csv'</span>, encoding<span class="op">=</span><span class="st">'latin1'</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Edad'</span>] <span class="op">=</span> pd.to_numeric(df[<span class="st">'Edad'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>edad <span class="op">=</span> df[<span class="st">'Edad'</span>].dropna()</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas </span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>q1  <span class="op">=</span> np.quantile(edad, <span class="fl">0.25</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>q3  <span class="op">=</span> np.quantile(edad, <span class="fl">0.75</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> q3 <span class="op">-</span> q1</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>low  <span class="op">=</span> q1 <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>high <span class="op">=</span> q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Q1:    </span><span class="sc">{</span>q1<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Q3:    </span><span class="sc">{</span>q3<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"IQR:   </span><span class="sc">{</span>iqr<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Límite inferior: </span><span class="sc">{</span>low<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Límite superior: </span><span class="sc">{</span>high<span class="sc">:.2f}</span><span class="ss"> años"</span>)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot </span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>plt.boxplot(edad, vert<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f"Boxplot edad: IQR=</span><span class="sc">{</span>iqr<span class="sc">:.2f}</span><span class="ss">, límites [</span><span class="sc">{</span>low<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Edad (años)"</span>)</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Q1:    21.00 años
Q3:    40.00 años
IQR:   19.00 años
Límite inferior: -7.50 años
Límite superior: 68.50 años</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-15-output-2.png" width="662" height="470" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="medidas-de-heterogeneidad" class="level2">
<h2 class="anchored" data-anchor-id="medidas-de-heterogeneidad">Medidas de heterogeneidad</h2>
<div id="8e83f49e" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'dataset_limpio.csv'</span>, encoding<span class="op">=</span><span class="st">'latin1'</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo y porcentaje por sexo</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>sexo_counts <span class="op">=</span> df[<span class="st">'Sexo'</span>].value_counts(dropna<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>sexo_pct <span class="op">=</span> df[<span class="st">'Sexo'</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>, dropna<span class="op">=</span><span class="va">True</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>resumen_sexo <span class="op">=</span> pd.DataFrame({</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Frecuencia'</span>: sexo_counts,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Porcentaje'</span>: sexo_pct.<span class="bu">round</span>(<span class="dv">1</span>).astype(<span class="bu">str</span>) <span class="op">+</span> <span class="st">' %'</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(resumen_sexo)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfica de barras</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>sexo_counts.plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span>[<span class="st">'#3266ad'</span>, <span class="st">'#e05c5c'</span>], edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Distribución de desapariciones por sexo'</span>)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Sexo'</span>)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Número de personas'</span>)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        Frecuencia Porcentaje
Sexo                         
HOMBRE       59938     76.2 %
MUJER        18733     23.8 %</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-16-output-2.png" width="663" height="374" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="medidas-de-concentración" class="level2">
<h2 class="anchored" data-anchor-id="medidas-de-concentración">Medidas de concentración</h2>
<hr>
</section>
</section>
<section id="correlación" class="level1">
<h1>Correlación</h1>
<ul>
<li>Generar la matriz de correlación (heatmap)<br>
</li>
<li>Indicar correlaciones más fuertes y más débiles</li>
</ul>
<hr>
</section>
<section id="hallazgos-importantes-y-limitaciones-del-análisis" class="level1">
<h1>Hallazgos importantes y limitaciones del análisis</h1>
<ol type="1">
<li>Alto porcentaje de datos faltantes en la columna Fecha de desaparición</li>
</ol>
<p>El 80 % de los registros carece de fecha de desaparición, lo que limita significativamente el análisis temporal y la identificación de tendencias a lo largo del tiempo.</p>
<ol start="2" type="1">
<li>Concentración de desapariciones en población joven (moda: 18 años)</li>
</ol>
<p>La distribución de edades muestra que la moda es de 18 años, lo que indica una concentración preocupante en población adolescente.</p>
<ol start="3" type="1">
<li>Rango típico de riesgo: entre 14 y 48 años</li>
</ol>
<p>Encontramos una desviación estándar de 17 años sobre la media de 31 años, el perfil típico de persona desaparecida oscila entre los 14 y 48 años. Los cuartiles confirman que el 50 % central de los casos tiene entre 21 años (Q1) y 40 años (Q3), afectando principalmente a población en etapa productiva y juvenil.</p>
<ol start="4" type="1">
<li>Estados que concentran la mayoría de las desapariciones registradas</li>
</ol>
<p>El análisis de clustering K-Means (k=4) sobre el total de desapariciones por entidad revela una concentración geográfica marcada. Los 5 estados con mayor volumen son: Tamaulipas, Estado de México, Veracruz, Michoacán y Sinaloa. Estos estados forman un cluster propio (Cluster 0) muy separado del resto del país, y coinciden con zonas de alta actividad del crimen organizado, corredores de tránsito y fronteras de alto riesgo.</p>
<ol start="5" type="1">
<li>Registros duplicados identificados por combinación de variables clave</li>
</ol>
<p>Se detectaron registros duplicados comparando Nombre, Primer Apellido, Segundo Apellido, Fecha de desaparición Entidad y Autoridad que reportó. Se optó por este subconjunto de variables porque el mismo nombre puede corresponder a reportes legítimos en distintas instituciones o entidades. Se conservó el primer registro de cada grupo duplicado con keep=‘first’.</p>
<ol start="6" type="1">
<li>Existencia de registros ELIMINADO: anonimización sistemática de datos</li>
</ol>
<p>El dataset contiene filas donde todas las columnas presentan valores como ‘ELIMINADO 1’, ‘ELIMINADO 2’, etc., indicando un mecanismo MNAR (Missing Not At Random). Estas filas fueron eliminadas durante la limpieza al no aportar información analítica. Su existencia sugiere procesos intencionales de anonimización o censura de datos.</p>
<ol start="7" type="1">
<li>Las desapariciones afectan predominantemente a hombres (76.2 %)</li>
</ol>
<p>Del total de registros con sexo registrado, el 76.2 % corresponde a hombres y el 23.8 % a mujeres. No obstante, dado que 38,076 registros (33 % del total) carecen de dato de sexo, la proporción real podría diferir de estos valores.</p>
<ol start="8" type="1">
<li></li>
</ol>
<hr>
</section>
<section id="reporte-final-hallazgos-y-limitaciones" class="level1">
<h1>Reporte final: hallazgos y limitaciones</h1>
<p>Entregar un reporte en PDF que incluya: - Objetivo y preguntas de análisis - Descripción del dataset asignado al equipo - Al menos 8 hallazgos principales sustentados con evidencia gráfica o tablas - Limitaciones del análisis: calidad de los datos, sesgos, variables faltantes y decisiones de limpieza - Conclusión.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>